# Generated by Django 4.1.2 on 2024-06-17 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('diagnostico', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=50)),
                ('comentario_rechazo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtencionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.atencion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.material')),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='mecanico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mecanico'),
        ),
    ]
