# Generated by Django 4.1.2 on 2024-06-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecanico', models.CharField(max_length=255)),
                ('zona', models.CharField(max_length=255)),
                ('pieza', models.CharField(max_length=255)),
                ('comentarios', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='atencionmaterial',
            name='atencion',
        ),
        migrations.RemoveField(
            model_name='atencionmaterial',
            name='material',
        ),
        migrations.DeleteModel(
            name='Atencion',
        ),
        migrations.DeleteModel(
            name='AtencionMaterial',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Mecanico',
        ),
    ]
