# Generated by Django 4.1.2 on 2024-06-17 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mantenimiento_remove_atencionmaterial_atencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
