# Generated by Django 4.1.2 on 2024-06-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mantenimiento_fecha_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('conf_pass', models.CharField(max_length=255)),
            ],
        ),
    ]
