# Generated by Django 4.1.2 on 2024-06-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_usuario_conf_pass_remove_usuario_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='comentarios',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='mecanico',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='pieza',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='zona',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='nombre',
            field=models.CharField(default='nombre', max_length=100),
            preserve_default=False,
        ),
    ]
