# Generated by Django 4.1.2 on 2024-06-27 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='descripcion',
            new_name='comentarios',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='nombre',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='mecanico',
            field=models.CharField(default='mecanico', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='pieza',
            field=models.CharField(default='pieza', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='zona',
            field=models.CharField(default='zona', max_length=255),
            preserve_default=False,
        ),
    ]
